version: '3.9'

networks:
  app-network:
    driver: bridge
services:
  postgres:
    image: postgres:14-alpine
    container_name: db-postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dados
    networks:
      - app-network
    restart: unless-stopped

  app:
    container_name: app-jsf
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - 8081:8080
    expose:
      - 8081  
    networks:
      - app-network
    depends_on:
      - postgres
