version: '3.9'

networks:
  app-network:
    driver: bridge
services:
  mysql:
    image: mysql:8
    container_name: db-app-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'dados'
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - app-network
    ports:
      - 3306:3306
    restart: unless-stopped 
