insert into ramo_atividade (id, descricao) values ( uuid_in(md5(random()::text || random()::text)::cstring), 'Distribuição de alimentos');
insert into ramo_atividade (id, descricao) values ( uuid_in(md5(random()::text || random()::text)::cstring), 'Telecomunicações');
insert into ramo_atividade (id, descricao) values ( uuid_in(md5(random()::text || random()::text)::cstring), 'Vestuário');
insert into ramo_atividade (id, descricao) values ( uuid_in(md5(random()::text || random()::text)::cstring), 'Lavanderia');
insert into ramo_atividade (id, descricao) values ( uuid_in(md5(random()::text || random()::text)::cstring), 'Gráfica');
insert into ramo_atividade (id, descricao) values ( uuid_in(md5(random()::text || random()::text)::cstring), 'Mecânica');
insert into ramo_atividade (id, descricao) values ( uuid_in(md5(random()::text || random()::text)::cstring), 'Turismo');
insert into ramo_atividade (id, descricao) values ( uuid_in(md5(random()::text || random()::text)::cstring), 'Saúde');
insert into ramo_atividade (id, descricao) values ( uuid_in(md5(random()::text || random()::text)::cstring), 'Educação');
insert into ramo_atividade (id, descricao) values ( uuid_in(md5(random()::text || random()::text)::cstring), 'Lazer');
